<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;


use Neoan3\Apps\Stateless;
use Neoan3\Frame\Moe;
use Neoan3\Model\UserModel;

class Login extends Moe
{
    function init()
    {
        $this->hook('main','login')->output();
    }
    function postLogin(array $body)
    {
        $user =  UserModel::login($body);
        return [
            'token' => Stateless::assign($user['id'],['all']),
            'user' => $user
        ];

    }

}
