<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Frame\Moe;
use Neoan3\Model\UserModel;

class Home extends Moe
{
    function init()
    {
        UserModel::create([
            'userName' => 'stefan',
            'password' => ['password'=>'123456'],
            'emails' => [
                ['email' => 'stefan@website.com']
            ]
        ]);
        $this->hook('main','home', $passIn);
        $this->output();
    }

}
